navbar:
  displayTitle: true
  displayLogo: false

search:
  enable: true

page:
  layout: normal  # options: normal, wide

footer:
  displayCopyright: true
  displayPoweredBy: true

youtubeDefaults:
  iframeAllowList: "accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
  referrerpolicy: "no-referrer"
  iframeStyle: "border:0; width:100%; aspect-ratio:16/9;"

blog:
    list:
      displayTags: true
      sortBy: date
      sortOrder: desc # or "asc"
      pagerSize: 20

    article:
      displayPagination: true

toc:
    displayTags: true    

theme:
  default: light

author:
  name: João Bugelli
  email: joaoalexsb@gmail.com

# adicionar descrição do site
description: ""

# add katex as engine to render latex
math:
  engine: katex
  katex:
    base: "https://cdn.jsdelivr.net/npm/katex@0.16.22/dist"